### Transacciones

GET http://localhost:3000/transacciones

###
GET http://localhost:3000/transacciones/1
###
POST http://localhost:3000/transacciones
Content-Type: application/json

{
  "IdCuentaOrigen": 1,
  "Monto": 1500,
  "Tipo": "retiro",
  "Descripcion": "Pago de servicios",
  "Estado": "completado",
  "Fecha": "2025-10-28T12:00:00.000Z"
}

###
PUT http://localhost:3000/transacciones/8
Content-Type: application/json

{
  "Estado": "completado"
}

###
DELETE http://localhost:3000/transacciones/1